# Generated by Django 5.2.15 on 2026-06-12 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("MECANICIEN", "Mécanicien"),
                            ("DEPANNAGE", "Dépannage / Remorquage"),
                            ("GARAGE", "Garage complet"),
                        ],
                        default="MECANICIEN",
                        max_length=20,
                    ),
                ),
                ("experience_years", models.IntegerField(default=0)),
                (
                    "price_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField(default=0.0)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
