# Generated by Django 6.0.6 on 2026-06-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_otp_code_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
